### ISSUE TITLE
Swift PM tag

### ISSUE THREAD

**Issue by yonaskolb** [BalestraPatrick/Stryng#5]
Swift PM requires versions to be tagged with semver which requires `major.minor.patch`.
Strying is only tagged with `0.2` which can't be pulled in. Is it possible to make a `0.2.1` release?

**Comment by BalestraPatrick** [comment]
@yonaskolb Done! https://github.com/BalestraPatrick/Stryng/releases/tag/0.2.1

**Comment by yonaskolb** [comment]
Thanks!
Sorry, I had the version numbers mixed up there 😄

**Comment by jameslittle230** [comment]
This might need to be reopened now that the version has been bumped to `0.4` -- Swift Package Manager doesn't recognize two-part version numbers (`0.4.0` would be a valid alternative) so when I try to pull in the package the only version that gets recognized is `0.2.1`.

**Comment by BalestraPatrick** [comment]
@jameslittle230 Fixed it! https://github.com/BalestraPatrick/Stryng/releases/tag/0.4.1
